### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by stowball** [cometchat-pro/javascript-react-chat-app#66]
### Describe the problem

After following the installation instructions and trying to run the project, I immediately get this error:

```
/Users/me/javascript-react-chat-app/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/me/javascript-react-chat-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/me/javascript-react-chat-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/me/javascript-react-chat-app/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/me/javascript-react-chat-app/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/me/javascript-react-chat-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/me/javascript-react-chat-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/me/javascript-react-chat-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/me/javascript-react-chat-app/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
```

### What was the expected behavior?

For the project to run

### Reproduction

1. Clone repo
2. Install dependencies
3. Run `npm start`

### Environment

> Please provide the following:

- Node.js v17.01
- MacOS 12.1 Montery Apple M1 Pro
- iTerm running in Rosetta mode

**Comment by aaliya-shaikh** [comment]
Please try to use the latest LTS node version as it is the most stable version of node i.e 16.14.0 . 
Node v17 has some bugs 
For ref: https://github.com/facebook/create-react-app/issues/11708#issuecomment-1012162852
And follow the Readme.MD instructions.

**Comment by stowball** [comment]
Thanks, that fixed it
